### PR TITLE
Define Java min/max memory to align with XNAT recommendations

### LINKED ISSUE #8: Align JVM memory allocation with XNAT recommendation
From here:
https://wiki.xnat.org/documentation/getting-started-with-xnat/xnat-installation-guide/prerequisites-for-installing-xnat

It's recommended that at a minimum you set the Java memory limits explicitly.

`CATALINA_OPTS="-Xms512m -Xmx1g -XX:+UseConcMarkSweepGC -XX:-OmitStackTraceInFastThrow"`

Just below, they note that 4g (i.e. 4 GV) is a reasonable size for Production

### PR DESCRIPTION
**Pull request by andrewbrock-sahmri**
Closes #8

### CODE REVIEW

**Comment by dean-taylor** [comment]
-Xms512m -Xmx4g -XX:+UseConcMarkSweepGC -XX:-OmitStackTraceInFastThrow
Suggestions:
* Move any default values hard wired into Tomcat to before `${CATALINA_OPTS}` so that passed user arguments can override fixed settings. Relies on precedence order of JVM interpretation of settings and may change. Would need a unit test to ensure that this does not happen as a regression.
* Move the default settings into the Docker image using the CATALINA_OPTS environment variable and not in the Tomcat settings directly. Will not apply settings to non-docker images builds and this may become a requirement.

**Comment by dean-taylor** [comment]
TEST for precedence order of JVM
$ docker run -it --rm --entrypoint "" cerds/xnat-web:1.8.2-dev bash -c "java -version; java -Xmx1G -XX:+PrintFlagsFinal -Xmx2G 2>/dev/null | grep MaxHeapSize"
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
    uintx MaxHeapSize                              := 2147483648                          {product}

**Comment by dean-taylor** [comment]
Just thought of option 3.
The settings file is a shell script so there could be logic to only apply default settings if not already supplied by the user.
Makes this file more complex for future work but would ensure consistent operability.

**Comment by andrewbrock-sahmri** [comment]
I've changed my approach in response to your feedback, and thinking about it a bit more.
I've introduced a new packer variable with the default values matching the XNAT doco. If someone wants to override it they can via:

1. Setting the packer variable at build time
2. Adding an override via a script in `/docker-entrypoint.d/`

We might not need both approaches though?

**Comment by andrewbrock-sahmri** [comment]
I'll close this and send a new PR with the approach agreed yesterday.

**Pull request closed without merging**
