### PR TITLE
xnat build v1.8.4.1

### PR DESCRIPTION
**Pull request by fxusyd**

### CODE REVIEW

**Comment by andrewbrock-sahmri** [comment]
Should we just delete lines rather than commenting them out?

**Comment by fxusyd** [comment]
Sure, definitely

**Comment by fxusyd** [comment]
thanks for reminding, removed the commented lines now

**Comment by fxusyd** [comment]
waiting for Mark's confirmation that standard xnat 1.8.4.1 includes the fix to allow long aaf username

**Pull request merged**
